In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr2 = np.random.randint(1, 10, size=(3, 3))
arr2

array([[4, 7, 4],
       [6, 4, 8],
       [1, 2, 2]], dtype=int32)

In [5]:
arr1.sum()

np.int64(55)

In [6]:
arr1.mean()

np.float64(5.5)

In [7]:
arr1.max()

np.int64(10)

In [8]:
arr1 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr1_modified = np.where(arr1 > 5, 0, arr1)
arr1_modified

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])